apiVersion: apps/v1
kind: Deployment
metadata:
  name: chai-app
  labels:
    app: chai-app
spec:
<<<<<<< HEAD
  replicas: 4
=======
  replicas: 3
>>>>>>> 57a006d0f2bde083e043e08546afc58c7f93d75d
  selector:
    matchLabels:
      app: chai-app
  template:
    metadata:
      labels:
        app: chai-app
    spec:
      containers:
      - name: chai-app
        image: nginx:1.25
        ports:
        - containerPort: 80
